export enum HanlightMusicTypes {
  GET_MUSIC = 'GET_MUSIC',
  GET_MUSIC_SUCCESS = 'GET_MUSIC_SUCCESS',
  GET_MUSIC_FAILURE = 'GET_MUSIC_FAILURE',

  POST_MUSIC = 'POST_MUSIC',
  POST_MUSIC_SUCCESS = 'POST_MUSIC_SUCCESS',
  POST_MUSIC_FAILURE = 'POST_MUSIC_FAILURE',

  GET_MUSIC_SEARCH = 'GET_MUSIC_SEARCH',
  GET_MUSIC_SEARCH_SUCCESS = 'GET_MUSIC_SEARCH_SUCCESS',
  GET_MUSIC_SEARCH_FAILURE = 'GET_MUSIC_SEARCH_FAILURE',

  TOGGLE_HM = 'TOGGLE_HM',

  RESET_SEARCH_LIST = 'RESET_SEARCH_LIST',
}
