export enum FestivalTypes {
  GET_LOL_TEAM = 'GET_LOL_TEAM',
  GET_LOL_TEAM_SUCCESS = 'GET_LOL_TEAM_SUCCESS',
  GET_LOL_TEAM_FAILURE = 'GET_LOL_TEAM_FAILURE',

  GET_MATCH = 'GET_MATCH',
  GET_MATCH_SUCCESS = 'GET_MATCH_SUCCESS',
  GET_MATCH_FAILURE = 'GET_MATCH_FAILURE',

  GET_SINGER = 'GET_SINGER',
  GET_SINGER_SUCCESS = 'GET_SINGER_SUCCESS',
  GET_SINGER_FAILURE = 'GET_SINGER_FAILURE',

  POST_SINGER_VOTE = 'POST_SINGER_VOTE',
  POST_SINGER_VOTE_SUCCESS = 'POST_SINGER_VOTE_SUCCESS',
  POST_SINGER_VOTE_FAILURE = 'POST_SINGER_VOTE_FAILURE',

  POST_LOL_VOTE = 'POST_LOL_VOTE',
  POST_LOL_VOTE_SUCCESS = 'POST_LOL_VOTE_SUCCESS',
  POST_LOL_VOTE_FAILURE = 'POST_LOL_VOTE_FAILURE',

  GET_FS_TIMETABLE = 'GET_FS_TIMETABLE',
  GET_FS_TIMETABLE_SUCCESS = 'GET_FS_TIMETABLE_SUCCESS',
  GET_FS_TIMETABLE_FAILURE = 'GET_FS_TIMETABLE_FAILURE',

  GET_SHOP_LIST = 'GET_SHOP_LIST',
  GET_SHOP_LIST_SUCCESS = 'GET_SHOP_LIST_SUCCESS',
  GET_SHOP_LIST_FAILURE = 'GET_SHOP_LIST_FAILURE',

  TOGGLE_MODAL = 'TOGGLE_MODAL',
}
