export enum FestivalTypes {
  GET_SHOP_LIST = 'GET_SHOP_LIST',
  GET_SHOP_LIST_SUCCESS = 'GET_SHOP_LIST_SUCCESS',
  GET_SHOP_LIST_FAILURE = 'GET_SHOP_LIST_FAILURE',

  TOGGLE_MODAL = 'TOGGLE_MODAL',
}
