export enum FestivalTypes {
  GET_LOL_TEAM = 'GET_LOL_TEAM',
  GET_LOL_TEAM_SUCCESS = 'GET_LOL_TEAM_SUCCESS',
  GET_LOL_TEAM_FAILURE = 'GET_LOL_TEAM_FAILURE',

  GET_MATCH = 'GET_MATCH',
  GET_MATCH_SUCCESS = 'GET_MATCH_SUCCESS',
  GET_MATCH_FAILURE = 'GET_MATCH_FAILURE',

  GET_SINGER = 'GET_SINGER',
  GET_SINGER_SUCCESS = 'GET_SINGER_SUCCESS',
  GET_SINGER_FAILURE = 'GET_SINGER_FAILURE',

  POST_SINGER_VOTE = 'POST_SINGER_VOTE',
  POST_SINGER_VOTE_SUCCESS = 'POST_SINGER_VOTE_SUCCESS',
  POST_SINGER_VOTE_FAILURE = 'POST_SINGER_VOTE_FAILURE',

  POST_LOL_VOTE = 'POST_LOL_VOTE',
  POST_LOL_VOTE_SUCCESS = 'POST_LOL_VOTE_SUCCESS',
  POST_LOL_VOTE_FAILURE = 'POST_LOL_VOTE_FAILURE',

  GET_FS_TIMETABLE = 'GET_FS_TIMETABLE',
  GET_FS_TIMETABLE_SUCCESS = 'GET_FS_TIMETABLE_SUCCESS',
  GET_FS_TIMETABLE_FAILURE = 'GET_FS_TIMETABLE_FAILURE',

  GET_PAY_SHOP_PURCHASE = 'GET_PAY_SHOP_PURCHASE',
  GET_PAY_SHOP_PURCHASE_SUCCESS = 'GET_PAY_SHOP_PURCHASE_SUCCESS',
  GET_PAY_SHOP_PURCHASE_FAILURE = 'GET_PAY_SHOP_PURCHASE_FAILURE',

  POST_ADMIN_MONEY = 'POST_ADMIN_MONEY',
  POST_ADMIN_MONEY_SUCCESS = 'POST_ADMIN_MONEY_SUCCESS',
  POST_ADMIN_MONEY_FAILURE = 'POST_ADMIN_MONEY_FAILURE',

  POST_ADMIN_MONEY_APPROVE = 'POST_ADMIN_MONEY_APPROVE',
  POST_ADMIN_MONEY_APPROVE_SUCCESS = 'POST_ADMIN_MONEY_APPROVE_SUCCESS',
  POST_ADMIN_MONEY_APPROVE_FAILURE = 'POST_ADMIN_MONEY_APPROVE_FAILURE',

  GET_ADMIN_MONEY_LIST = 'GET_ADMIN_MONEY_LIST',
  GET_ADMIN_MONEY_LIST_SUCCESS = 'GET_ADMIN_MONEY_LIST_SUCCESS',
  GET_ADMIN_MONEY_LIST_FAILURE = 'GET_ADMIN_MONEY_LIST_FAILURE',

  GET_SHOP_LIST = 'GET_SHOP_LIST',
  GET_SHOP_LIST_SUCCESS = 'GET_SHOP_LIST_SUCCESS',
  GET_SHOP_LIST_FAILURE = 'GET_SHOP_LIST_FAILURE',

  POST_SHOP_PURCHASE = 'POST_SHOP_PURCHASE',
  POST_SHOP_PURCHASE_SUCCESS = 'POST_SHOP_PURCHASE_SUCCESS',
  POST_SHOP_PURCHASE_FAILURE = 'POST_SHOP_PURCHASE_FAILURE',

  GET_RECEIPT_LIST = 'GET_RECEIPT_LIST',
  GET_RECEIPT_LIST_SUCCESS = 'GET_RECEIPT_LIST_SUCCESS',
  GET_RECEIPT_LIST_FAILURE = 'GET_RECEIPT_LIST_FAILURE',

  POST_RECEIPT_CONFIRM = 'POST_RECEIPT_CONFIRM',
  POST_RECEIPT_CONFIRM_SUCCESS = 'POST_RECEIPT_CONFIRM_SUCCESS',
  POST_RECEIPT_CONFIRM_FAILURE = 'POST_RECEIPT_CONFIRM_FAILURE',

  TOGGLE_MODAL = 'TOGGLE_MODAL',

  GET_MONEY = 'GET_MONEY',
  GET_MONEY_SUCCESS = 'GET_MONEY_SUCCESS',
  GET_MONEY_FAILURE = 'GET_MONEY_FAILURE',

  GET_ADMIN_BOOL = 'GET_ADMIN_BOOL',
  GET_ADMIN_BOOL_SUCCESS = 'GET_ADMIN_BOOL_SUCCESS',
  GET_ADMIN_BOOL_FAILURE = 'GET_ADMIN_BOOL_FAILURE',
}
